### ISSUE TITLE
Updated optimal plans for caldera

### ISSUE THREAD

**Issue by haz** [AI-Planning/api-tools#15]
The optimal plans for the Caldera domain (released in the 2018 IPC) were computed by Patrik Haslum: [caldera-sols.tar.gz](https://github.com/AI-Planning/api-tools/files/9183456/caldera-sols.tar.gz)

These should be added as solutions to the relevant problems (domains 131+143). These are just for the unsplit variant. All solutions were computed to be optimal, and this is the conversation snippet indicating as such:

> I have found what should be optimal solutions to all
> the instances of the caldera domain (opt and sat sets). The biggest
> problem in the sat set took just over 20 minutes to solve (I think I can
> trim that down a bit).
>
> The domain is not quite delete-free (some actions have a negative
> precondition (not (created ?v)) which is effectively "deleted" by adding
> (created ?v)), but it's close enough to monotone that a small tweak to
> my h+ solver was enough to make it generate valid plans for all
> problems; since it's a relaxation, the plan costs should never be
> greater than the optimal. (The grounding problem was trickier to deal
> with...) The plan costs fall within the bounds you provided. In most
> cases it's equal to your current upper bound, in a few cases it's one
> action less.
>
> Attaching the plan files (vlog.txt for each set is a summary of the
> validator output, plus your bounds).

### Update String
`hsps/test_ilb -ce -flx -ho`

### TODO
- [ ] Get optimal submission string
- [ ] Update plans (/upper bound)
- [ ] Update lower bounds w/ message string
